[book]
title = "Note to self: Record even the smallest something"
authors = ["lCyou"]
language = "en"

[output.html]
default-theme = "rust"
additional-css = ["theme/custom.css"]
additional-js = ["theme/custom.js"] 
mathjax-support = true              
no-section-label = true       
git-repository-url = "https://github.com/lCyou/mdbook-daily"
git-repository-icon = "fab-github"

[output.html.fold]
enable = true
level = 0