name: publish my note

on:
  workflow_dispatch:
  schedule: 
    - cron:  '0 18 * * 0'  # Weekly at 3am JST on Monday

permissions: 
  contents: write
  pages: write
  id-token: write

jobs:
  update_summary:
    uses:  ./.github/workflows/update-summary.yml

  deploy:
    needs: update_summary
    uses: ./.github/workflows/mdbook.yml
